name: Node.JS CI/CD

on:
  push:
    branches: [main]

jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: NPM install, build, test and report
        run: |
          npm install
          npm test
          npm run coverage:badge
        env:
          MONGO_URL_TEST: ${{ secrets.MONGO_URL_TEST }}  
          NODE_ENV: ${{ secrets.NODE_ENV }}  
          SECRET_KEY_DB: ${{ secrets.SECRET_KEY_DB }}  
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}  

  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Add remote origin to Heroku
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      
      - name: Deploy code to heroku
        run: git push heroku main